language: python
sudo: false

#addons:
#  apt:
#    source:
#      - r-packages-trusty
#    packages:
#      - libassimp3v5
#      - libassimp-dev

before_install:
  - wget https://github.com/assimp/assimp/archive/v4.1.0.tar.gz
  - tar -xzvf v4.1.0.tar.gz
  - pushd assimp-4.1.0 && cmake CMakeLists.txt -G 'Unix Makefiles' && make && make install && popd

  - pip install -r ./requirements.txt

install:
  - python setup.py build
  - python setup.py install