language: python
sudo: false

addons:
  apt:
    packages:
      - libassimp3v5
      - libassimp-dev

before_install:
- pip install -r ./requirements.txt

install:
  - python setup.py build
  - python setup.py install