language: python
python:
  - "2.7"
  - "3.5"
  
sudo: false

addons:
  apt:
    packages:
      - libassimp3
      - libassimp-dev

before_install:
  - pip install -r ./requirements.txt

install:
  - python setup.py build
  - python setup.py install

script:
  - python -m unittest ./tests/test_simple.py