language: python
python:
  - "2.7"
#  - "3.6"

cache: pip

sudo: required
env:
  global:
    - CIBW_ENVIRONMENT="PYPANDOC_PANDOC='/root/bin/pandoc' LOCAL_CMAKE='True'"
    - CIBW_BEFORE_BUILD="{python} ci_scripts/assimpDownload.py && {pip} install numpy && {pip} install cython && {python} setup.py build_ext --force"
services:
  - docker

addons:
  apt:
    packages:
      - libassimp3
      - libassimp-dev

before_install:
  - pip install -r ./requirements.txt

install:
  - python setup.py build_ext
  - python setup.py install

script:
  - pushd tests && python -m unittest test_simple && popd
  - pip install cibuildwheel==0.7.0
  - cibuildwheel --output-dir wheelhouse